"""
Emit the appendix table of per-station decay-fit results as LaTeX.

The appendix decay figures (station_decay.py) deliberately show only the SHAPE of each
settling curve: their panel titles carry the station and tau, and the y axis is relative
(uGal about the reported value), so the absolute gravity appears nowhere. This table is
where those numbers live, so the two are complementary rather than redundant.

Reads  Data/Gravimetry/Processed/decay_fits.csv  (written by station_decay.py, which is
also where Date/Time come from) and writes a \\input-able .tex into the thesis repo.

Layout: TWO blocks of rows side by side, so 124 stations fit on one page. Dates are
shortened to MM-DD and times to HH:MM -- the year and seconds carry no information here
and cost ~8 characters per row, which is what decides whether the table fits.

`g` is the REPORTED value the pipeline consumes: the weighted mean for settled stations,
the decay asymptote g_inf for settling ones (the `settled` column says which). That is
the same convention station_decay.py uses, so table and figures agree.

Run:  python make_decay_table.py
"""

import pandas as pd
import sys as _sys, pathlib as _pl
_sys.path.insert(0, str(_pl.Path(__file__).resolve().parents[1]))   # Code/ for plot_utils
from plot_utils import THESIS
from grav_utils import PROC_DIR

FITS = PROC_DIR / "decay_fits.csv"
OUT = THESIS / "Appendices" / "decay_fits_table.tex"

NBLOCKS = 2          # side-by-side row blocks; 2 -> 62 rows each -> one page
FONT = r"\scriptsize"
COLSEP = "3pt"       # inter-column padding; LOWER = narrower table


def fmt_row(r):
    """One station -> the 8 cells of a block."""
    tau = "--" if r["settled"] else f"{r['tau_min']:.1f}"
    status = "settled" if r["settled"] else "decaying"
    if not r["converged"]:
        status = r"no fit"
    return [f"{int(r['Line'])}", f"{int(r['Station'])}",
            str(r["Date"])[5:].replace("/", "-"),      # YYYY/MM/DD -> MM-DD
            str(r["Time"])[:5],                        # HH:MM:SS   -> HH:MM
            f"{r['g_inf']:.3f}", f"{r['SE_g_inf']:.3f}", tau, status]


def main():
    d = pd.read_csv(FITS).sort_values(["Line", "Station"]).reset_index(drop=True)
    rows = [fmt_row(r) for _, r in d.iterrows()]
    per = -(-len(rows) // NBLOCKS)                     # ceil
    blocks = [rows[i * per:(i + 1) * per] for i in range(NBLOCKS)]
    blocks = [b + [[""] * 8] * (per - len(b)) for b in blocks]   # pad to equal length

    head = (r"L & Stn & Date & Start & $g$ (mGal) & SE & $\tau$ (min) & Status")
    spec = "rrllrrrl"
    colspec = ("@{}" + (" @{\\hspace{1.2em}} ".join([spec] * NBLOCKS)) + "@{}")

    L = []
    L.append("% Auto-generated by Code/Grav/make_decay_table.py -- do not edit by hand.")
    L.append(r"\begin{table}[htbp]")
    L.append(r"  \centering")
    L.append(f"  \\setlength{{\\tabcolsep}}{{{COLSEP}}}")
    # NB the short (list-of-tables) caption reads "Per-station gravimeter decay-fit
    # results". That word was added by hand in the GENERATED .tex, which this script
    # overwrites -- so it lived here for exactly one regeneration. It is now in the
    # generator, which is what makes the "do not edit by hand" banner above true.
    # The station count is derived, not typed, for the same reason.
    L.append(r"  \caption[Per-station gravimeter decay-fit results]{Decay-fit results "
             r"for all \num{" + str(len(rows)) + r"} gravity stations, ordered by line "
             r"and station. $g$ is the "
             r"reported station gravity: the weighted mean for settled stations and "
             r"the fitted asymptote $g_\infty$ for settling ones, as indicated by the "
             r"status column. $\tau$ is the fitted settling time constant, given only "
             r"where a decay was fitted. Times are the start of the first reading. The "
             r"corresponding curves are shown in "
             r"Figs.~\ref{fig:decay-l2}--\ref{fig:decay-l5}.}")
    L.append(r"  \label{tab:decay-fits}")
    L.append(f"  {FONT}")
    L.append(f"  \\begin{{tabular}}{{{colspec}}}")
    L.append(r"    \toprule")
    L.append("    " + " & ".join([head] * NBLOCKS) + r" \\")
    L.append(r"    \midrule")
    for i in range(per):
        cells = []
        for b in blocks:
            cells += b[i]
        L.append("    " + " & ".join(cells) + r" \\")
    L.append(r"    \bottomrule")
    L.append(r"  \end{tabular}")
    L.append(r"\end{table}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"  saved -> {OUT}")
    print(f"  {len(rows)} stations, {NBLOCKS} blocks of {per} rows, font {FONT}")


if __name__ == "__main__":
    main()
